include(${CMAKE_CURRENT_LIST_DIR}/../3dparty/catch2/sweetshot_3p.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/../3dparty/cmakerc/sweetshot_3p.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/../3dparty/lodepng/sweetshot_3p.cmake)
if (SWEETSHOT_PNG_BACKEND STREQUAL "resvg")
    include(${CMAKE_CURRENT_LIST_DIR}/../3dparty/resvg/sweetshot_3p.cmake)
elseif (SWEETSHOT_PNG_BACKEND STREQUAL "lunasvg")
    include(${CMAKE_CURRENT_LIST_DIR}/../3dparty/lunasvg/sweetshot_3p.cmake)
endif ()
include(${CMAKE_CURRENT_LIST_DIR}/../3dparty/sweetline/sweetshot_3p.cmake)
